import { Counselor } from '../types';

export const COUNSELORS_DATA: Counselor[] = [
  {
    id: 'counselor-1',
    name: 'Dr. Sarah Chen, Psy.D.',
    title: 'Senior Clinical Psychologist & Academic Stress Specialist',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    badge: 'Campus Lead',
    experienceYears: 11,
    rating: 4.9,
    specializations: ['Academic Stress', 'Exam Anxiety', 'Perfectionism', 'Imposter Syndrome'],
    sessionTypes: ['In-Person Wellness Center', 'Secure Video Call'],
    intro: 'Hi! I specialize in helping students navigate overwhelming academic workloads, thesis panic, and perfectionist exhaustion with practical, compassionate CBT techniques.',
    approach: 'Collaborative, practical, and solution-focused. We work together on tangible coping mechanisms you can test during midterms and finals.',
    availableDays: ['Today', 'Tomorrow', 'This Thursday', 'Next Monday'],
    availableSlots: {
      'Today': ['2:00 PM', '3:30 PM', '4:45 PM'],
      'Tomorrow': ['10:00 AM', '11:15 AM', '1:30 PM', '4:00 PM'],
      'This Thursday': ['9:30 AM', '1:00 PM', '3:00 PM'],
      'Next Monday': ['11:00 AM', '2:30 PM', '4:00 PM'],
    },
  },
  {
    id: 'counselor-2',
    name: 'Marcus Vance, LMFT',
    title: 'Student Wellness Counselor & Identity Specialist',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    badge: 'First-Gen Ally',
    experienceYears: 8,
    rating: 4.95,
    specializations: ['Identity & Transition', 'First-Gen Student Care', 'Relationships', 'Burnout'],
    sessionTypes: ['In-Person Wellness Center', 'Secure Video Call'],
    intro: 'I create an open, affirming space for students navigating university transitions, family expectations, identity exploration, and finding belonging on campus.',
    approach: 'Relational, narrative, and deeply affirming. No clinical jargon—just real, supportive conversations tailored to your authentic life context.',
    availableDays: ['Today', 'Tomorrow', 'This Friday'],
    availableSlots: {
      'Today': ['4:15 PM'],
      'Tomorrow': ['1:00 PM', '2:15 PM', '5:00 PM'],
      'This Friday': ['10:30 AM', '12:00 PM', '2:00 PM'],
    },
  },
  {
    id: 'counselor-3',
    name: 'Dr. Elena Rostova, Ph.D.',
    title: 'Behavioral Sleep & Stress Reduction Specialist',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400',
    badge: 'Mindfulness Expert',
    experienceYears: 14,
    rating: 4.88,
    specializations: ['Sleep & Insomnia', 'Chronic Stress', 'Mindfulness', 'Health/Wellbeing'],
    sessionTypes: ['In-Person Wellness Center', 'Secure Video Call'],
    intro: 'Irregular sleep schedules and racing thoughts at 3 AM are common in college. We work on resetting circadian wellness, easing somatic tension, and nervous system regulation.',
    approach: 'Integrative mindfulness-based stress reduction (MBSR) combined with behavioral sleep medicine and somatic relaxation techniques.',
    availableDays: ['Tomorrow', 'This Thursday', 'This Friday'],
    availableSlots: {
      'Tomorrow': ['9:00 AM', '11:00 AM', '3:00 PM'],
      'This Thursday': ['10:00 AM', '1:30 PM', '4:30 PM'],
      'This Friday': ['9:30 AM', '11:30 AM'],
    },
  },
  {
    id: 'counselor-4',
    name: 'Priya Patel, LCSW',
    title: 'Anxiety & Interpersonal Relationships Counselor',
    photo: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=400',
    badge: 'Peer Favorite',
    experienceYears: 7,
    rating: 4.92,
    specializations: ['Social Anxiety', 'Roommate & Friend Dynamics', 'Loneliness', 'Grief & Loss'],
    sessionTypes: ['In-Person Wellness Center', 'Secure Video Call'],
    intro: 'Feeling lonely or misunderstood among thousands of peers is tough. I help students unpack social anxiety, build authentic friendships, and set healthy boundaries.',
    approach: 'Warm, empathic, and grounding. A non-judgmental space where you can share messy feelings and leave with clarity and emotional safety.',
    availableDays: ['Today', 'Tomorrow', 'Next Monday'],
    availableSlots: {
      'Today': ['5:00 PM'],
      'Tomorrow': ['10:30 AM', '2:00 PM', '3:45 PM'],
      'Next Monday': ['10:00 AM', '1:00 PM', '3:30 PM'],
    },
  },
  {
    id: 'counselor-5',
    name: 'Alex Rivera, MS, LPC',
    title: 'Career & Future Direction Counselor',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    badge: 'Grad & Senior Lead',
    experienceYears: 6,
    rating: 4.85,
    specializations: ['Career Anxiety', 'Financial Stress', 'Major Indecision', 'Life Transitions'],
    sessionTypes: ['In-Person Wellness Center', 'Secure Video Call'],
    intro: 'Stressed about career prospects, internships, or what comes after graduation? Let’s dissect the pressure, separate external expectations from your values, and chart steady steps.',
    approach: 'Values-driven, proactive counseling focused on clarifying purpose and managing existential career dread.',
    availableDays: ['Tomorrow', 'This Thursday', 'This Friday'],
    availableSlots: {
      'Tomorrow': ['11:30 AM', '1:30 PM', '4:30 PM'],
      'This Thursday': ['9:00 AM', '12:00 PM', '2:30 PM'],
      'This Friday': ['1:00 PM', '3:30 PM'],
    },
  },
];
